### ISSUE TITLE
Add new `SparseEqualTo[V]` predicate

### ISSUE THREAD

**Issue by tixxit** [stripe/brushfire#41]
Create a `SparseEqualTo[V]` predicate that defaults to `false` for missing data (eg `None`).

**Comment by tixxit** [comment]
I believe this is covered by `IsPresent` predicate. I'm still not a huge fan of either of these, but not sure of a better way to handle it quite yet.

**Comment by NathanHowell** [comment]
Just spent a little bit debugging some unit tests and was surprised to find the default predicates returning true for missing features. Seems like it might be better to opt-in to this instead of having to opt-out.

**Comment by tixxit** [comment]
Perhaps it would make the most sense to push this decision to `TreeTraversal` instead. We would then not deal with missing features in predicates at all and, instead, depend on people using actual `Option` types for feature values if they want to represent missing features in their tree. This would certainly simplify the predicates.
